run:
  deadline: 5m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - tests
    - src
    - node_modules
    - dist
    - assets
    - .storybook

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
linters:
  enable-all: true
