language: ruby
services:
  - docker

stages:
  - name: Release

jobs:
  - stage: Release
    arch: amd64
    os: linux
    script:
      - make release TAG=`echo $TRAVIS_COMMIT | cut -c -7`

after_success:
  - bash <(curl -s https://codecov.io/bash)
